version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    restart: always

  backend:
    image: python:3.10
    ports:
      - 8081:8080
    entrypoint: make run
    working_dir: /opt/app
    volumes:
      - ./backend:/opt/app
      - venv:/opt/venv
    environment:
      - VENVDIR=/opt/venv
      - MIRO_CLIENT_ID=${MIRO_CLIENT_ID}
      - MIRO_SECRET=${MIRO_SECRET}
    restart: always

  frontend:
    image: node:lts-alpine
    ports:
      - 8082:8080
    entrypoint: npm run serve
    working_dir: /opt/app
    volumes:
      - ./frontend:/opt/app
      - node_modules:/opt/node_modules
    environment:
      - NPM_CONFIG_PREFIX=/opt/node_modules
    depends_on:
      - backend
    restart: always

volumes:
  venv:
  node_modules:
